// <auto-generated />
using System;
using KanaTrainer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanaTrainer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240816174008_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KanaTrainer.Data.Models.Kana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KanaOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KanaRomaji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KanaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kanas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75540d8d-2236-4cc8-9d79-ff34ef35d38e"),
                            KanaOriginal = "あ",
                            KanaRomaji = "a",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("fa933675-cd78-402a-ae1a-8d3cf74ac743"),
                            KanaOriginal = "い",
                            KanaRomaji = "i",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("590ce245-2598-4bc6-af5d-ad0978aad49b"),
                            KanaOriginal = "う",
                            KanaRomaji = "u",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("ac9a1603-8065-43d7-9a1b-3765d7d9ee06"),
                            KanaOriginal = "え",
                            KanaRomaji = "e",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("db202534-901c-41a4-97f8-dd0ee16822d6"),
                            KanaOriginal = "お",
                            KanaRomaji = "o",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("e2d5aa08-e1cd-4e4a-a871-943700c367f1"),
                            KanaOriginal = "か",
                            KanaRomaji = "ka",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("c19ea8cc-1d1b-4057-ab0e-675bcb521d40"),
                            KanaOriginal = "き",
                            KanaRomaji = "ki",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("97578ddf-7f13-47ca-9e63-17f3a2a26240"),
                            KanaOriginal = "く",
                            KanaRomaji = "ku",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("6fa3681a-a588-40f6-b63e-f285809e8681"),
                            KanaOriginal = "け",
                            KanaRomaji = "ke",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("a3ae3826-1a1e-4585-984b-af86f76f8b0b"),
                            KanaOriginal = "こ",
                            KanaRomaji = "ko",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("d8364b6d-aecc-4f74-950c-084b16d6c3bf"),
                            KanaOriginal = "さ",
                            KanaRomaji = "sa",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("91cf84d8-8896-4243-bbca-d997d4a856a7"),
                            KanaOriginal = "し",
                            KanaRomaji = "shi",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("aafd6276-51c5-4fd6-9e9c-022076801bec"),
                            KanaOriginal = "す",
                            KanaRomaji = "su",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("9fc5e7f7-36ff-435c-8415-33b91c9c469b"),
                            KanaOriginal = "せ",
                            KanaRomaji = "se",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("da1bf444-c0de-4fea-9fa4-eb195cce89e2"),
                            KanaOriginal = "そ",
                            KanaRomaji = "so",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("dbdd209d-ece0-441d-b4bf-9ef0eebc7311"),
                            KanaOriginal = "た",
                            KanaRomaji = "ta",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("ee0067c6-4a28-44e4-9bc8-83c01b6c7ce5"),
                            KanaOriginal = "ち",
                            KanaRomaji = "chi",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("2f197318-2d32-4ea0-81bd-0d16bb2b7f3a"),
                            KanaOriginal = "つ",
                            KanaRomaji = "tsu",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("aa3002e3-310d-4a44-be4d-db6ac89e5201"),
                            KanaOriginal = "て",
                            KanaRomaji = "te",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("9966626d-872d-461f-8334-4392fde27c31"),
                            KanaOriginal = "と",
                            KanaRomaji = "to",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("2ecc1fdb-8705-46be-a5b5-487d8200e0c5"),
                            KanaOriginal = "な",
                            KanaRomaji = "na",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("826f1d7f-9537-4f98-95c4-123093d75684"),
                            KanaOriginal = "に",
                            KanaRomaji = "ni",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("dd2781c3-f734-472a-8ebd-21a05802016f"),
                            KanaOriginal = "ぬ",
                            KanaRomaji = "nu",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("88467ab8-8840-4599-b256-da0900e3839b"),
                            KanaOriginal = "ね",
                            KanaRomaji = "ne",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("1cd7f2a9-c416-4053-b25e-b82b4b998785"),
                            KanaOriginal = "の",
                            KanaRomaji = "no",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("ac61511c-26da-48ea-9f5a-5cae84553e99"),
                            KanaOriginal = "は",
                            KanaRomaji = "ha",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("5c9ee8e7-31d3-4bbb-a0f8-9d966335345e"),
                            KanaOriginal = "ひ",
                            KanaRomaji = "hi",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("fb9dbcca-c2c7-43c2-ad19-68e38b5e62d5"),
                            KanaOriginal = "ふ",
                            KanaRomaji = "fu",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("c8f5bff8-5255-4c2a-acdd-d29f4dc6cd00"),
                            KanaOriginal = "へ",
                            KanaRomaji = "he",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("0d9d5df0-461f-47f7-8cfa-34bc23eb73b3"),
                            KanaOriginal = "ほ",
                            KanaRomaji = "ho",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("cae6a412-8ce6-4f47-a0ec-e93e410ef417"),
                            KanaOriginal = "ま",
                            KanaRomaji = "ma",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("2f6b5521-2c57-4383-befe-ec2b859e7118"),
                            KanaOriginal = "み",
                            KanaRomaji = "mi",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("66872e13-899a-45f7-9598-38e78ee4f381"),
                            KanaOriginal = "む",
                            KanaRomaji = "mu",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("a3193b86-fb95-43ab-b142-515f6ed0ee87"),
                            KanaOriginal = "め",
                            KanaRomaji = "me",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("fa585454-b4d6-489e-a7b4-19c7bf8fd92e"),
                            KanaOriginal = "も",
                            KanaRomaji = "mo",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("c3433c92-94a9-408d-a01e-452ab5112532"),
                            KanaOriginal = "や",
                            KanaRomaji = "ya",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("578bf9c7-f4d7-4984-85d5-6ed883c08e72"),
                            KanaOriginal = "ゆ",
                            KanaRomaji = "yu",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("50e65da6-17d7-4e89-9f12-7a131b030648"),
                            KanaOriginal = "よ",
                            KanaRomaji = "yo",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("2fecef30-4935-4382-b59c-b42d3b4e7079"),
                            KanaOriginal = "ら",
                            KanaRomaji = "ra",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("22a82163-8742-4876-9ea2-b5c6aa7c4a4a"),
                            KanaOriginal = "り",
                            KanaRomaji = "ri",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("00d7e01b-0175-4143-a0b3-4d23cf74f946"),
                            KanaOriginal = "る",
                            KanaRomaji = "ru",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("1b54b879-0237-431d-a243-63123d40143d"),
                            KanaOriginal = "れ",
                            KanaRomaji = "re",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("3756e3ed-aaa6-4adf-988f-b5f00bf6e995"),
                            KanaOriginal = "ろ",
                            KanaRomaji = "ro",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("ca314a9f-ebaa-448a-9c6b-0c53b2b8ce88"),
                            KanaOriginal = "わ",
                            KanaRomaji = "wa",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("fc24be7d-417b-4770-a695-63673c8a2786"),
                            KanaOriginal = "を",
                            KanaRomaji = "wo",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("29805b4b-10cf-4ccb-b0f2-7f9afbe9043b"),
                            KanaOriginal = "が",
                            KanaRomaji = "ga",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("08528afb-28a9-4d19-aa9f-4a81a796213d"),
                            KanaOriginal = "ぎ",
                            KanaRomaji = "gi",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("563364ba-b3c5-4dcd-b055-ff9baafe4c33"),
                            KanaOriginal = "ぐ",
                            KanaRomaji = "gu",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("d8aa7193-5df3-4cd8-a5f5-7c78129ffadc"),
                            KanaOriginal = "げ",
                            KanaRomaji = "ge",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("6965752d-6368-4b6c-9cba-9a4e72718e39"),
                            KanaOriginal = "ご",
                            KanaRomaji = "go",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("4bc71f7a-3d5f-4656-bc3f-bfa3e46abc33"),
                            KanaOriginal = "ざ",
                            KanaRomaji = "za",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("86e535ea-b20b-4557-9755-0c034e730ea0"),
                            KanaOriginal = "じ",
                            KanaRomaji = "ji",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("62196cc8-ce37-4623-a80c-75807967660c"),
                            KanaOriginal = "ず",
                            KanaRomaji = "zu",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("8757edfb-2a5b-40a1-9be8-7bc0b941f4b7"),
                            KanaOriginal = "ぜ",
                            KanaRomaji = "ze",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("f7d30fb3-afa2-4ac8-96a5-8ed2d785f857"),
                            KanaOriginal = "ぞ",
                            KanaRomaji = "zo",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("b741155b-6cd5-4c3d-b429-f7f09b02988c"),
                            KanaOriginal = "だ",
                            KanaRomaji = "da",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("b90eab8b-1a6c-4718-a124-94cfd590cc60"),
                            KanaOriginal = "ぢ",
                            KanaRomaji = "ji",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("aeeced9f-7e92-4276-b12a-d628331cb0ea"),
                            KanaOriginal = "づ",
                            KanaRomaji = "zu",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("2eba6fc8-5369-4e9e-803b-df68777f9540"),
                            KanaOriginal = "で",
                            KanaRomaji = "de",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("d09b213f-8143-47a0-af86-6627d4870e25"),
                            KanaOriginal = "ど",
                            KanaRomaji = "do",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("ec07fb24-0315-480c-85cf-d31c4ab858b6"),
                            KanaOriginal = "ば",
                            KanaRomaji = "ba",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("815df60c-4917-4667-9b25-01071e418fa4"),
                            KanaOriginal = "び",
                            KanaRomaji = "bi",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("d369ed49-9530-4ad2-bfca-1c093ce9f5a1"),
                            KanaOriginal = "ぶ",
                            KanaRomaji = "bu",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("1aa6c297-61b5-4475-b670-868704766b9a"),
                            KanaOriginal = "べ",
                            KanaRomaji = "be",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("5b492af1-a973-49df-be5a-14792c7bf7ab"),
                            KanaOriginal = "ぼ",
                            KanaRomaji = "bo",
                            KanaType = "Hiragana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("43efa4c7-e349-4859-b883-19460ab02b2d"),
                            KanaOriginal = "ぱ",
                            KanaRomaji = "pa",
                            KanaType = "Hiragana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("cfc20c30-cc57-4a72-a1c4-b4ed000d68d8"),
                            KanaOriginal = "ぴ",
                            KanaRomaji = "pi",
                            KanaType = "Hiragana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("de870734-c0e6-474f-b8bd-156114f6502d"),
                            KanaOriginal = "ぷ",
                            KanaRomaji = "pu",
                            KanaType = "Hiragana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("e5875a5c-aabb-45ac-8266-326db594c68e"),
                            KanaOriginal = "ぺ",
                            KanaRomaji = "pe",
                            KanaType = "Hiragana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("d84bf4d7-b29a-46fc-b10f-2c1378bca034"),
                            KanaOriginal = "ぽ",
                            KanaRomaji = "po",
                            KanaType = "Hiragana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("a1ac703c-3756-46ae-b209-894da95cb53f"),
                            KanaOriginal = "きゃ",
                            KanaRomaji = "kya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("6e207ea1-fdb5-4662-9a80-12b00cc4f52e"),
                            KanaOriginal = "きゅ",
                            KanaRomaji = "kyu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("31c71176-abc7-4599-991d-a06b066d55fc"),
                            KanaOriginal = "きょ",
                            KanaRomaji = "kyo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("fd187151-a38c-451e-a8b7-656790d49433"),
                            KanaOriginal = "しゃ",
                            KanaRomaji = "sha",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("c5568a7d-ef5e-49f4-be75-4055d53aad61"),
                            KanaOriginal = "しゅ",
                            KanaRomaji = "shu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("e8c79f5d-6715-46b4-b4a5-ed785001f366"),
                            KanaOriginal = "しょ",
                            KanaRomaji = "sho",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("b3bfd9e6-06fa-494f-9e93-37a8246427fb"),
                            KanaOriginal = "ちゃ",
                            KanaRomaji = "cha",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("1abe747e-71e7-4cf0-bc41-e357ab8ed798"),
                            KanaOriginal = "ちゅ",
                            KanaRomaji = "chu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("cf6b0935-5232-487c-a030-8ea0b4572368"),
                            KanaOriginal = "ちょ",
                            KanaRomaji = "cho",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("6b0a568b-2ba4-49bb-9be8-944fbe0c854c"),
                            KanaOriginal = "にゃ",
                            KanaRomaji = "nya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("854e8b7e-a45e-4ce7-8552-79956228952d"),
                            KanaOriginal = "にゅ",
                            KanaRomaji = "nyu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("e66bd758-3d7c-46a0-9f85-99e5e933309c"),
                            KanaOriginal = "にょ",
                            KanaRomaji = "nyo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("a026960b-fe29-40c3-bc93-0dba67f9fe24"),
                            KanaOriginal = "ひゃ",
                            KanaRomaji = "hya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("473442ea-ea6e-47e6-aad5-4b9916a77f87"),
                            KanaOriginal = "ひゅ",
                            KanaRomaji = "hyu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("c5ecc107-09b5-46e0-a1c6-e10fc7b2c6fe"),
                            KanaOriginal = "ひょ",
                            KanaRomaji = "hyo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("b8e17665-0e70-4686-8ff9-4e1ff5a6291b"),
                            KanaOriginal = "みゃ",
                            KanaRomaji = "mya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("ecf71fa2-96d0-4471-8eb7-2239913907f0"),
                            KanaOriginal = "みゅ",
                            KanaRomaji = "myu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("64e216e9-0c4d-4a16-aa60-595a70ca8d8c"),
                            KanaOriginal = "みょ",
                            KanaRomaji = "myo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("61c0e7f5-6052-49b8-8949-ad7e614775b2"),
                            KanaOriginal = "りゃ",
                            KanaRomaji = "rya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("508d95ec-5409-45b9-9984-9a148e26c5bb"),
                            KanaOriginal = "りゅ",
                            KanaRomaji = "ryu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("8d9cc2bf-d0ec-43b1-85f3-7aae7d2c0249"),
                            KanaOriginal = "りょ",
                            KanaRomaji = "ryo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("4f67541c-ab1a-4452-ad64-d0388595c5cb"),
                            KanaOriginal = "ぎゃ",
                            KanaRomaji = "gya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("2eefaefe-cd78-4e1b-b535-90b86338cbf5"),
                            KanaOriginal = "ぎゅ",
                            KanaRomaji = "gyu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("d7c6bd12-ffb0-43ae-8891-fd27bfe714e2"),
                            KanaOriginal = "ぎょ",
                            KanaRomaji = "gyo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("5fd16917-69aa-4789-824d-b694bc0cca67"),
                            KanaOriginal = "じゃ",
                            KanaRomaji = "ja",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("38fb4d4d-f7d9-41e0-b64a-e349e3244582"),
                            KanaOriginal = "じゅ",
                            KanaRomaji = "ju",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("f9395e02-d323-4ad5-9ae1-62491fe42a3b"),
                            KanaOriginal = "じょ",
                            KanaRomaji = "jo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("655f0397-fc6f-4884-8bc8-55c709bcd3c7"),
                            KanaOriginal = "ぢゃ",
                            KanaRomaji = "ja",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("fb80026e-1e80-4c69-bed9-09943d21db26"),
                            KanaOriginal = "ぢゅ",
                            KanaRomaji = "ju",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("8b50c85c-82ef-4c5e-881e-46ddc91639d9"),
                            KanaOriginal = "ぢょ",
                            KanaRomaji = "jo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("84f1ae89-b848-44b2-884a-f281faff2038"),
                            KanaOriginal = "びゃ",
                            KanaRomaji = "bya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("8719683e-2a25-45aa-b887-622f08619421"),
                            KanaOriginal = "びゅ",
                            KanaRomaji = "byu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("90d73389-0e68-43d9-9b1f-2935c57ad627"),
                            KanaOriginal = "びょ",
                            KanaRomaji = "byo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("30c73e5c-6f7f-49c9-ab23-c34e2d4dda56"),
                            KanaOriginal = "ぴゃ",
                            KanaRomaji = "pya",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("dc1488b1-459b-4614-874b-d0a1e4c98ddd"),
                            KanaOriginal = "ぴゅ",
                            KanaRomaji = "pyu",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("b489a159-b090-4604-8eb6-380a98198f5d"),
                            KanaOriginal = "ぴょ",
                            KanaRomaji = "pyo",
                            KanaType = "Hiragana Yōon"
                        },
                        new
                        {
                            Id = new Guid("b602e67b-2a97-45e2-a48b-f8d94e6909b0"),
                            KanaOriginal = "ん",
                            KanaRomaji = "n",
                            KanaType = "Hiragana"
                        },
                        new
                        {
                            Id = new Guid("72ed6873-7c11-45ba-8064-17c05207a709"),
                            KanaOriginal = "ア",
                            KanaRomaji = "a",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("f10fda03-6953-46b6-85b7-d16b6f50e6a5"),
                            KanaOriginal = "イ",
                            KanaRomaji = "i",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("9d9eca69-bb0d-4737-a38f-199a1105049d"),
                            KanaOriginal = "ウ",
                            KanaRomaji = "u",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("79b43b03-6f27-42af-9aa6-97b1a6275c52"),
                            KanaOriginal = "エ",
                            KanaRomaji = "e",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("545ccd27-439d-4a1c-8733-0aeec12ad118"),
                            KanaOriginal = "オ",
                            KanaRomaji = "o",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("268f5428-54de-4f18-a481-fd3e6ed1803f"),
                            KanaOriginal = "カ",
                            KanaRomaji = "ka",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("254f5722-c2e2-4eae-a7f1-7016fa6d3a7f"),
                            KanaOriginal = "キ",
                            KanaRomaji = "ki",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("d02d458e-f336-4cd7-9873-c4b7c157861a"),
                            KanaOriginal = "ク",
                            KanaRomaji = "ku",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("2e7d7dc6-f29c-4f08-918f-25de42b747df"),
                            KanaOriginal = "ケ",
                            KanaRomaji = "ke",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("5bb292c3-c5c8-4613-8cba-114c89c08f4d"),
                            KanaOriginal = "コ",
                            KanaRomaji = "ko",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("7fc2e4d1-3f12-4c98-97e4-40d8d9943625"),
                            KanaOriginal = "サ",
                            KanaRomaji = "sa",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("5fec005d-7699-44c6-ac04-00674c407746"),
                            KanaOriginal = "シ",
                            KanaRomaji = "shi",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("977bb739-6d28-47d2-811c-eebd16a301ff"),
                            KanaOriginal = "ス",
                            KanaRomaji = "su",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("b50a6028-3985-47d7-9210-ef19c03496b6"),
                            KanaOriginal = "セ",
                            KanaRomaji = "se",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("a51970b7-400f-42a0-81c8-69d19701d514"),
                            KanaOriginal = "ソ",
                            KanaRomaji = "so",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("490c6794-5427-4361-a7af-a1ec00dbdb39"),
                            KanaOriginal = "タ",
                            KanaRomaji = "ta",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("cc05517a-3a5b-4d46-a3ac-b6bdc0ce0de4"),
                            KanaOriginal = "チ",
                            KanaRomaji = "chi",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("c16a1909-fad9-4efc-99f0-f507a9daa753"),
                            KanaOriginal = "ツ",
                            KanaRomaji = "tsu",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("0bc73973-95f3-4844-8724-53ac4caadf1a"),
                            KanaOriginal = "テ",
                            KanaRomaji = "te",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("9428c06c-11d9-42ca-836b-2e4fb98e871e"),
                            KanaOriginal = "ト",
                            KanaRomaji = "to",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("d1683e5a-78fd-47c7-9ce3-877bf5ca636a"),
                            KanaOriginal = "ナ",
                            KanaRomaji = "na",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("4699894c-9911-433c-8cf2-ed36773acd80"),
                            KanaOriginal = "ニ",
                            KanaRomaji = "ni",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("c07a8998-3975-4158-a50d-9129637841ee"),
                            KanaOriginal = "ヌ",
                            KanaRomaji = "nu",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("b1d5524b-54ab-4aea-a139-46edcdb7bfdf"),
                            KanaOriginal = "ネ",
                            KanaRomaji = "ne",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("d6378948-4381-4904-a927-49ac1ab1547e"),
                            KanaOriginal = "ノ",
                            KanaRomaji = "no",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("b48ea537-6a4c-42bd-9715-30987a567fa3"),
                            KanaOriginal = "ハ",
                            KanaRomaji = "ha",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("084ee46e-024b-46f6-8aea-1c785bd80624"),
                            KanaOriginal = "ヒ",
                            KanaRomaji = "hi",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("5a2ef20f-340c-4224-a29b-307814250849"),
                            KanaOriginal = "フ",
                            KanaRomaji = "fu",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("3b60da22-f670-4ba0-945f-57c6aeb875a4"),
                            KanaOriginal = "ヘ",
                            KanaRomaji = "he",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("06b84260-f40e-4b12-aa52-c1a1888659ed"),
                            KanaOriginal = "ホ",
                            KanaRomaji = "ho",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("8488e95c-1353-4073-80fb-bcfdbeeda78d"),
                            KanaOriginal = "マ",
                            KanaRomaji = "ma",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("38423f3a-c30f-4222-ab6c-c5242cd19523"),
                            KanaOriginal = "ミ",
                            KanaRomaji = "mi",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("cc3b4c36-f2d0-4805-a64c-c28ada2ec61d"),
                            KanaOriginal = "ム",
                            KanaRomaji = "mu",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("2fd9de04-8324-4e29-be82-131ba0d668f5"),
                            KanaOriginal = "メ",
                            KanaRomaji = "me",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("7cfbbab7-5c72-4011-b8ac-2d260897a127"),
                            KanaOriginal = "モ",
                            KanaRomaji = "mo",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("4d9dc207-03f9-4d88-917b-c0cca0d1fb71"),
                            KanaOriginal = "ヤ",
                            KanaRomaji = "ya",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("bce1af76-d0c1-4f63-a95d-753bcdd09542"),
                            KanaOriginal = "ユ",
                            KanaRomaji = "yu",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("142ce3d7-d673-434b-900b-9bdfd4dd69bc"),
                            KanaOriginal = "ヨ",
                            KanaRomaji = "yo",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("20342114-5397-432c-b838-edeb153a0385"),
                            KanaOriginal = "ラ",
                            KanaRomaji = "ra",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("66c8248a-64e0-44fb-9f7d-47ee525d9777"),
                            KanaOriginal = "リ",
                            KanaRomaji = "ri",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("e0844fe3-6086-4c0e-b34a-be3ddc523dba"),
                            KanaOriginal = "ル",
                            KanaRomaji = "ru",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("7f607a45-2a7e-4ee7-ac6f-ff1a03cf682d"),
                            KanaOriginal = "レ",
                            KanaRomaji = "re",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("2d78bee6-f2ad-4037-be81-35023dd5c82c"),
                            KanaOriginal = "ロ",
                            KanaRomaji = "ro",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("c286a172-4839-44cb-86ce-7b519f6b7635"),
                            KanaOriginal = "ワ",
                            KanaRomaji = "wa",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("6435372c-28ed-4917-a87c-834fe92539fb"),
                            KanaOriginal = "ヲ",
                            KanaRomaji = "wo",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("cb151fe6-8ff3-4742-a014-16b77dc5c37d"),
                            KanaOriginal = "ン",
                            KanaRomaji = "n",
                            KanaType = "Katakana"
                        },
                        new
                        {
                            Id = new Guid("b45a52a6-7509-411d-8799-191a6aadef71"),
                            KanaOriginal = "ガ",
                            KanaRomaji = "ga",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("a1de1b6a-c269-4538-a13b-21028fa7d3ff"),
                            KanaOriginal = "ギ",
                            KanaRomaji = "gi",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("98ce56a9-5025-4c1b-92d2-a25d17579137"),
                            KanaOriginal = "グ",
                            KanaRomaji = "gu",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("b96d273f-4ffd-4827-b471-1f3506c96e65"),
                            KanaOriginal = "ゲ",
                            KanaRomaji = "ge",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("3b27ed3b-65d7-4220-a59e-0d6682ec4a72"),
                            KanaOriginal = "ゴ",
                            KanaRomaji = "go",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("f1b04aac-196f-4cfb-8993-e8c702a96bbe"),
                            KanaOriginal = "ザ",
                            KanaRomaji = "za",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("f53ed849-d641-4a28-b386-f3770fc417f8"),
                            KanaOriginal = "ジ",
                            KanaRomaji = "ji",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("de7ecd51-6634-42bf-a7f7-fd4663bc7890"),
                            KanaOriginal = "ズ",
                            KanaRomaji = "zu",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("d2619644-b90d-4974-a48c-5a1d67174f80"),
                            KanaOriginal = "ゼ",
                            KanaRomaji = "ze",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("074d1979-6a8f-4fff-8254-b3f7f1296f21"),
                            KanaOriginal = "ゾ",
                            KanaRomaji = "zo",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("776226eb-43dc-4efa-859d-1c30ae39110f"),
                            KanaOriginal = "ダ",
                            KanaRomaji = "da",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("a2c4ccf1-8400-4afa-82e4-aeb2e696db15"),
                            KanaOriginal = "ヂ",
                            KanaRomaji = "ji",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("689fba92-4ed1-4e13-b521-26ab68d9601a"),
                            KanaOriginal = "ヅ",
                            KanaRomaji = "zu",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("5249c0fa-d64f-44a8-b527-751476e522c3"),
                            KanaOriginal = "デ",
                            KanaRomaji = "de",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("43617178-49c3-42ad-98c7-f30856d71862"),
                            KanaOriginal = "ド",
                            KanaRomaji = "do",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("a968be98-acef-4e52-90fb-6de1d24b6eeb"),
                            KanaOriginal = "バ",
                            KanaRomaji = "ba",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("8fd8287f-fea2-4c11-9191-ae3d30a32de1"),
                            KanaOriginal = "ビ",
                            KanaRomaji = "bi",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("71d0303b-b5f9-4fc9-b586-2b62cbc47cdf"),
                            KanaOriginal = "ブ",
                            KanaRomaji = "bu",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("f287ead5-faf3-44b0-84fa-bdd6fb590be8"),
                            KanaOriginal = "ベ",
                            KanaRomaji = "be",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("3d1a3b7f-4fc0-45b3-9398-d997dd876030"),
                            KanaOriginal = "ボ",
                            KanaRomaji = "bo",
                            KanaType = "Katakana Dakuon"
                        },
                        new
                        {
                            Id = new Guid("6a42e812-82a6-4251-be2b-a15d898fe38c"),
                            KanaOriginal = "パ",
                            KanaRomaji = "pa",
                            KanaType = "Katakana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("1e1ac7a8-321f-4785-91bf-02f50df71289"),
                            KanaOriginal = "ピ",
                            KanaRomaji = "pi",
                            KanaType = "Katakana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("5b9a62be-e94a-48d5-8bf2-81b3d0e824a5"),
                            KanaOriginal = "プ",
                            KanaRomaji = "pu",
                            KanaType = "Katakana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("36bc347d-fb47-44ca-905e-8d9220a6669b"),
                            KanaOriginal = "ペ",
                            KanaRomaji = "pe",
                            KanaType = "Katakana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("48bd59e3-e9c9-4d8c-97fb-015a0b8af241"),
                            KanaOriginal = "ポ",
                            KanaRomaji = "po",
                            KanaType = "Katakana Handakuon"
                        },
                        new
                        {
                            Id = new Guid("7de80c2c-8ede-4ad7-a9d2-813fc024c47d"),
                            KanaOriginal = "キャ",
                            KanaRomaji = "kya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("186d93d9-e692-4512-abd6-284d8520845e"),
                            KanaOriginal = "キュ",
                            KanaRomaji = "kyu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("252f2a79-f2f0-466f-a8a3-70607bdf04b6"),
                            KanaOriginal = "キョ",
                            KanaRomaji = "kyo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("68e64af5-9e22-44be-89b9-b3c79f1dd819"),
                            KanaOriginal = "シャ",
                            KanaRomaji = "sha",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("d8a36eba-3ba7-493c-877a-e4ea6309c55a"),
                            KanaOriginal = "シュ",
                            KanaRomaji = "shu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("31bcefe2-03c6-44e8-b686-3247c134049d"),
                            KanaOriginal = "ショ",
                            KanaRomaji = "sho",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("c19a6e68-bf75-446a-8d78-e59c8ad12dad"),
                            KanaOriginal = "チャ",
                            KanaRomaji = "cha",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("86122ad2-6892-4f93-8d85-2aad85f811cd"),
                            KanaOriginal = "チュ",
                            KanaRomaji = "chu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("17e9f1f3-b6a3-4506-b816-c86e614d2313"),
                            KanaOriginal = "チョ",
                            KanaRomaji = "cho",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("ced74a96-8e9b-454d-b1e0-08f4d6e97ad0"),
                            KanaOriginal = "ニャ",
                            KanaRomaji = "nya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("7285d6cc-4e5a-44c5-9b43-e0e04d45fd17"),
                            KanaOriginal = "ニュ",
                            KanaRomaji = "nyu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("e988647e-632e-46a2-8347-e4d133ff2de8"),
                            KanaOriginal = "ニョ",
                            KanaRomaji = "nyo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("6f024071-59d6-4839-9d84-5294605b0b02"),
                            KanaOriginal = "ヒャ",
                            KanaRomaji = "hya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("eda8ade3-3c40-4d15-987b-64bd5dde03f6"),
                            KanaOriginal = "ヒュ",
                            KanaRomaji = "hyu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("b3e98e15-588a-4093-9e5a-f266c51e5790"),
                            KanaOriginal = "ヒョ",
                            KanaRomaji = "hyo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("38bcea4b-8e48-4b10-b4f4-3e2ac55d4e5f"),
                            KanaOriginal = "ミャ",
                            KanaRomaji = "mya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("bc1f4295-0219-4ce5-8c6b-43d2c92a1be3"),
                            KanaOriginal = "ミュ",
                            KanaRomaji = "myu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("61ea9541-9763-4abf-8727-30a0b17a659e"),
                            KanaOriginal = "ミョ",
                            KanaRomaji = "myo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("d0a19b69-a2b4-4869-9c51-8d7744f51bf9"),
                            KanaOriginal = "リャ",
                            KanaRomaji = "rya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("e48e1681-2f9f-4623-a512-502edcae10ce"),
                            KanaOriginal = "リュ",
                            KanaRomaji = "ryu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("e8219f1b-3127-4010-9cbe-1dc1e345eaca"),
                            KanaOriginal = "リョ",
                            KanaRomaji = "ryo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("0e219284-2ae1-4bd1-8387-35c3b3e4fa51"),
                            KanaOriginal = "ギャ",
                            KanaRomaji = "gya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("9d71d301-24b4-4847-ba6b-ce6c0372da3a"),
                            KanaOriginal = "ギュ",
                            KanaRomaji = "gyu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("9e37e52f-6fcd-4a06-805b-7b80590a1c58"),
                            KanaOriginal = "ギョ",
                            KanaRomaji = "gyo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("d2fafc57-a921-4795-b034-8c5fb4b5fc88"),
                            KanaOriginal = "ジャ",
                            KanaRomaji = "ja",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("9235821f-04c4-4810-a6f1-5459f807ee61"),
                            KanaOriginal = "ジュ",
                            KanaRomaji = "ju",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("93cd04fa-4b8b-44a3-8bad-f5d25bb4d597"),
                            KanaOriginal = "ジョ",
                            KanaRomaji = "jo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("bb47f661-ae85-4353-bdf8-bdca1ffedcf5"),
                            KanaOriginal = "ヂャ",
                            KanaRomaji = "ja",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("292dec5a-bc40-4af5-8a03-6772ae164565"),
                            KanaOriginal = "ヂュ",
                            KanaRomaji = "ju",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("fbba720d-63f9-4075-b347-119917f6c948"),
                            KanaOriginal = "ヂョ",
                            KanaRomaji = "jo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("4ca2dabf-a2d3-4463-b720-c76bc1789790"),
                            KanaOriginal = "ビャ",
                            KanaRomaji = "bya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("c66348cd-5302-486b-8efb-68ffaa4c2d85"),
                            KanaOriginal = "ビュ",
                            KanaRomaji = "byu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("1079c397-5f88-4e5e-b164-cbe173c98511"),
                            KanaOriginal = "ビョ",
                            KanaRomaji = "byo",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("1d87da89-e02e-4c16-9607-96a1d476fa73"),
                            KanaOriginal = "ピャ",
                            KanaRomaji = "pya",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("e60fa465-1009-4504-8467-1bc9cebf8577"),
                            KanaOriginal = "ピュ",
                            KanaRomaji = "pyu",
                            KanaType = "Katakana Yōon"
                        },
                        new
                        {
                            Id = new Guid("5cf5c89b-ac83-4ea7-84f3-7d00de00c126"),
                            KanaOriginal = "ピョ",
                            KanaRomaji = "pyo",
                            KanaType = "Katakana Yōon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
